dataroot_H: ./trainsets/Sub/DRealSR/HR
dataroot_R: ./trainsets/Sub/DRealSR/LR
pca_matrices_root: ./deg/pca

blur_kernel_size1: 21
kernel_list1: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob1: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
sinc_prob1: 0.1
blur_sigma1: [0.2, 1.5]
betag_range1: [0.5, 2.0]
betap_range1: [1, 1.5]

blur_kernel_size2: 11
kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
sinc_prob2: 0.1
blur_sigma2: [0.2, 1.0]
betag_range2: [0.5, 2.0]
betap_range2: [1, 1.5]

final_sinc_prob: 0.8

use_sharpener: false
resize_hq: false
# Queue size of training pool, this should be multiples of batch_size.
queue_size: 256
# the first degradation process
resize_prob1: [0.2, 0.7, 0.1] # up, down, keep
resize_range1: [0.3, 1.5]
gaussian_noise_prob1: 0.5
noise_range1: [1, 15]
poisson_scale_range1: [0.05, 2]
gray_noise_prob1: 0.4
jpeg_range1: [60, 100]

# the second degradation process
scale: 4
blur_prob: 0.5
resize_prob2: [0.3, 0.4, 0.3] # up, down, keep
resize_range2: [0.6, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 12]
poisson_scale_range2: [0.05, 1.0]
gray_noise_prob2: 0.4
jpeg_range2: [60, 100]